In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pyspark as ps
import os

plt.style.use('ggplot')

In [2]:
spark = (ps.sql.SparkSession
        .builder
        .master('local[4]')
        .appName('capstone1')
        .getOrCreate()
        )
sc = spark.sparkContext

In [3]:
sc

In [4]:
spark

In [5]:
from pyspark.sql.types import *

schema = StructType([
    StructField('ResponseID', StringType(), True),
    StructField('ExtendedSessionID', StringType(), True),
    StructField('UserID', StringType(), True),
    StructField('ScenarioOrder', IntegerType(), True),
    StructField('Intervention', IntegerType(), True),
    StructField('PedPed', IntegerType(), True),
    StructField('Barrier', IntegerType(), True),
    StructField('CrossingSignal', IntegerType(), True),
    StructField('AttributeLevel', StringType(), True),
    StructField('ScenarioTypeStrict', StringType(), True),
    StructField('ScenarioType', StringType(), True),
    StructField('DefaultChoice', StringType(), True),
    StructField('NonDefaultChoice', StringType(), True),
    StructField('DefaultChoiceOmission', IntegerType(), True),
    StructField('NumberOfCharacters', IntegerType(), True),
    StructField('DiffNumberOfCharacters', IntegerType(), True),
    StructField('Saved', IntegerType(), True),
    StructField('Template', StringType(), True),
    StructField('DescriptionShown', IntegerType(), True),
    StructField('LeftHand', IntegerType(), True),
    StructField('UserCountry3', StringType(), True),
    StructField('Man', IntegerType(), True),
    StructField('Woman', IntegerType(), True),
    StructField('Pregnant', IntegerType(), True),
    StructField('Stroller', IntegerType(), True),
    StructField('OldMan', IntegerType(), True),
    StructField('OldWoman', IntegerType(), True),
    StructField('Boy', IntegerType(), True),
    StructField('Girl', IntegerType(), True),
    StructField('Homeless', IntegerType(), True),
    StructField('LargeWoman', IntegerType(), True),
    StructField('LargeMan', IntegerType(), True),
    StructField('Criminal', IntegerType(), True),
    StructField('MaleExecutive', IntegerType(), True),
    StructField('FemaleExecutive', IntegerType(), True),
    StructField('FemaleAthlete', IntegerType(), True),
    StructField('MaleAthlete', IntegerType(), True),
    StructField('FemaleDoctore', IntegerType(), True),
    StructField('MaleDoctor', IntegerType(), True),
    StructField('Dog', IntegerType(), True),
    StructField('Cat', IntegerType(), True),  
])

In [6]:
df = spark.read.csv('./data/SharedResponses.csv', schema=schema, header=True)

In [7]:
df.printSchema()

root
 |-- ResponseID: string (nullable = true)
 |-- ExtendedSessionID: string (nullable = true)
 |-- UserID: string (nullable = true)
 |-- ScenarioOrder: integer (nullable = true)
 |-- Intervention: integer (nullable = true)
 |-- PedPed: integer (nullable = true)
 |-- Barrier: integer (nullable = true)
 |-- CrossingSignal: integer (nullable = true)
 |-- AttributeLevel: string (nullable = true)
 |-- ScenarioTypeStrict: string (nullable = true)
 |-- ScenarioType: string (nullable = true)
 |-- DefaultChoice: string (nullable = true)
 |-- NonDefaultChoice: string (nullable = true)
 |-- DefaultChoiceOmission: integer (nullable = true)
 |-- NumberOfCharacters: integer (nullable = true)
 |-- DiffNumberOfCharacters: integer (nullable = true)
 |-- Saved: integer (nullable = true)
 |-- Template: string (nullable = true)
 |-- DescriptionShown: integer (nullable = true)
 |-- LeftHand: integer (nullable = true)
 |-- UserCountry3: string (nullable = true)
 |-- Man: integer (nullable = true)
 |-- Woman: integer (nullable = true)
 |-- Pregnant: integer (nullable = true)
 |-- Stroller: integer (nullable = true)
 |-- OldMan: integer (nullable = true)
 |-- OldWoman: integer (nullable = true)
 |-- Boy: integer (nullable = true)
 |-- Girl: integer (nullable = true)
 |-- Homeless: integer (nullable = true)
 |-- LargeWoman: integer (nullable = true)
 |-- LargeMan: integer (nullable = true)
 |-- Criminal: integer (nullable = true)
 |-- MaleExecutive: integer (nullable = true)
 |-- FemaleExecutive: integer (nullable = true)
 |-- FemaleAthlete: integer (nullable = true)
 |-- MaleAthlete: integer (nullable = true)
 |-- FemaleDoctore: integer (nullable = true)
 |-- MaleDoctor: integer (nullable = true)
 |-- Dog: integer (nullable = true)
 |-- Cat: integer (nullable = true)

In [8]:
df.count()

70332355

### Create SQL table 'mm'

In [47]:
df.createOrReplaceTempView('mm')

In [48]:
query = '''
SELECT *
FROM mm
LIMIT 10
'''

spark.sql(query).toPandas()

,ResponseID,ExtendedSessionID,UserID,ScenarioOrder,Intervention,PedPed,Barrier,CrossingSignal,AttributeLevel,ScenarioTypeStrict,...,LargeMan,Criminal,MaleExecutive,FemaleExecutive,FemaleAthlete,MaleAthlete,FemaleDoctore,MaleDoctor,Dog,Cat
0,2222bRQqBTZ6dLnPH,32757157_6999801415950060.0,6999801415950060,7,0,0,0,1,Fit,Fitness,...,0,0,0,0,1,2,0,0,0,0
1,2222sJk4DcoqXXi98,1043988516_3525281295.0,3525281295,2,0,0,0,0,Rand,Random,...,0,0,1,0,0,0,0,0,0,0
2,2223CNmvTr2Coj4wp,-1613944085_422160228641876.0,422160228641876,10,0,1,0,1,Female,Gender,...,0,0,0,1,0,0,0,0,0,0
3,2223Xu54ufgjcyMR3,1425316635_327833569077076.0,327833569077076,11,0,0,1,0,Old,Age,...,0,0,0,0,0,0,0,0,0,0
4,2223jMWDEGNeszivb,-1683127088_785070916172117.0,785070916172117,8,0,1,0,2,More,Utilitarian,...,0,1,1,0,1,0,0,0,1,0
5,22244vvSZfn4J9Zop,1525185249_1436495773909467.0,1436495773909470,11,0,0,1,0,Low,Social Status,...,0,0,0,0,0,0,0,0,0,0
6,2224H2QBFKNsMmRQc,1661661891_4304873273230329.0,4304873273230330,11,0,1,0,0,Female,Gender,...,0,0,0,1,0,0,1,0,0,0
7,2224YxTZcu4sJqTSD,-887960483_174929057557052.0,174929057557052,6,0,0,0,2,Hoomans,Species,...,0,0,0,0,1,1,0,0,0,0
8,2224g4ytARX4QT5rB,213978760_9992828917431898.0,9992828917431900,7,0,0,1,0,Less,Utilitarian,...,0,0,0,0,1,0,1,0,0,1
9,2224kBG72574tbZD3,737909459_839962439872333.0,839962439872333,12,0,0,1,0,Old,Age,...,0,0,0,0,0,0,0,0,0,0

In [51]:
query = '''
SELECT ScenarioType, DefaultChoice, count(*)
FROM mm
GROUP BY ScenarioType, DefaultChoice

'''

spark.sql(query).toPandas()

    ScenarioType DefaultChoice  count(1)
0            Age         Young  11583880
1        Fitness           Fit  10811634
2           None          None        74
3    Utilitarian          More  12527288
4         Gender          Male  11967330
5         Random          None   7507350
6  Social Status          High   3890417
7        Species       Hoomans  12044382

### Move limited # of rows to a Pandas DF for EDA

In [11]:
pdf = df.limit(100_000).toPandas()

In [12]:
pdf.head()

,ResponseID,ExtendedSessionID,UserID,ScenarioOrder,Intervention,PedPed,Barrier,CrossingSignal,AttributeLevel,ScenarioTypeStrict,...,LargeMan,Criminal,MaleExecutive,FemaleExecutive,FemaleAthlete,MaleAthlete,FemaleDoctore,MaleDoctor,Dog,Cat
0,2222bRQqBTZ6dLnPH,32757157_6999801415950060.0,6999801415950060,7,0,0,0,1,Fit,Fitness,...,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0
1,2222sJk4DcoqXXi98,1043988516_3525281295.0,3525281295,2,0,0,0,0,Rand,Random,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2223CNmvTr2Coj4wp,-1613944085_422160228641876.0,422160228641876,10,0,1,0,1,Female,Gender,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2223Xu54ufgjcyMR3,1425316635_327833569077076.0,327833569077076,11,0,0,1,0,Old,Age,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2223jMWDEGNeszivb,-1683127088_785070916172117.0,785070916172117,8,0,1,0,2,More,Utilitarian,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [13]:
pdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 41 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ResponseID              100000 non-null  object
 1   ExtendedSessionID       100000 non-null  object
 2   UserID                  99991 non-null   object
 3   ScenarioOrder           100000 non-null  int32
 4   Intervention            100000 non-null  int32
 5   PedPed                  100000 non-null  int32
 6   Barrier                 100000 non-null  int32
 7   CrossingSignal          100000 non-null  int32
 8   AttributeLevel          100000 non-null  object
 9   ScenarioTypeStrict      100000 non-null  object
 10  ScenarioType            99999 non-null   object
 11  DefaultChoice           89462 non-null   object
 12  NonDefaultChoice        89462 non-null   object
 13  DefaultChoiceOmission   89462 non-null   float64
 14  NumberOfCharacters      99999 non-null   float64
 15  DiffNumberOfCharacters  99999 non-null   float64
 16  Saved                   100000 non-null  int32
 17  Template                86891 non-null   object
 18  DescriptionShown        86891 non-null   float64
 19  LeftHand                86891 non-null   float64
 20  UserCountry3            98996 non-null   object
 21  Man                     99999 non-null   float64
 22  Woman                   99999 non-null   float64
 23  Pregnant                99999 non-null   float64
 24  Stroller                99999 non-null   float64
 25  OldMan                  99999 non-null   float64
 26  OldWoman                99999 non-null   float64
 27  Boy                     99999 non-null   float64
 28  Girl                    99999 non-null   float64
 29  Homeless                99999 non-null   float64
 30  LargeWoman              99999 non-null   float64
 31  LargeMan                99999 non-null   float64
 32  Criminal                99999 non-null   float64
 33  MaleExecutive           99999 non-null   float64
 34  FemaleExecutive         99999 non-null   float64
 35  FemaleAthlete           99999 non-null   float64
 36  MaleAthlete             99999 non-null   float64
 37  FemaleDoctore           99999 non-null   float64
 38  MaleDoctor              99999 non-null   float64
 39  Dog                     99999 non-null   float64
 40  Cat                     99999 non-null   float64
dtypes: float64(25), int32(6), object(10)
memory usage: 29.0+ MB

In [15]:
pdf.describe()

,ScenarioOrder,Intervention,PedPed,Barrier,CrossingSignal,DefaultChoiceOmission,NumberOfCharacters,DiffNumberOfCharacters,Saved,DescriptionShown,...,LargeMan,Criminal,MaleExecutive,FemaleExecutive,FemaleAthlete,MaleAthlete,FemaleDoctore,MaleDoctor,Dog,Cat
count,100000.000000,100000.0,100000.000000,100000.000000,100000.000000,89462.000000,99999.000000,99999.000000,100000.00000,86891.000000,...,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000
mean,6.741770,0.0,0.450480,0.215510,0.685410,0.492131,3.078281,0.570146,0.46393,0.274608,...,0.158432,0.059071,0.105701,0.106531,0.192102,0.189082,0.097831,0.096021,0.174862,0.172632
std,3.780925,0.0,0.497544,0.411178,0.856534,0.499941,1.468290,1.149558,0.49870,0.446319,...,0.444673,0.254876,0.345673,0.347424,0.523319,0.519744,0.335144,0.331123,0.571481,0.564407
min,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.000000,0.0,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,10.000000,0.0,1.000000,0.000000,2.000000,1.000000,4.000000,0.000000,1.00000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,14.000000,0.0,1.000000,1.000000,2.000000,1.000000,5.000000,4.000000,1.00000,1.000000,...,5.000000,3.000000,4.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,5.000000

In [24]:
survey_schema = StructType([
    StructField('ResponseID', StringType(), True),
    StructField('ExtendedSessionID', StringType(), True),
    StructField('UserID', StringType(), True),
    StructField('ScenarioOrder', IntegerType(), True),
    StructField('Intervention', IntegerType(), True),
    StructField('PedPed', IntegerType(), True),
    StructField('Barrier', IntegerType(), True),
    StructField('CrossingSignal', IntegerType(), True),
    StructField('AttributeLevel', StringType(), True),
    StructField('ScenarioTypeStrict', StringType(), True),
    StructField('ScenarioType', StringType(), True),
    StructField('DefaultChoice', StringType(), True),
    StructField('NonDefaultChoice', StringType(), True),
    StructField('DefaultChoiceOmission', IntegerType(), True),
    StructField('NumberOfCharacters', IntegerType(), True),
    StructField('DiffNumberOfCharacters', IntegerType(), True),
    StructField('Saved', IntegerType(), True),
    StructField('Template', StringType(), True),
    StructField('DescriptionShown', IntegerType(), True),
    StructField('LeftHand', IntegerType(), True),
    StructField('UserCountry3', StringType(), True),
    StructField('Review_age', IntegerType(), True),
    StructField('Review_education', StringType(), True),
    StructField('Review_gender', StringType(), True),
    StructField('Review_income', IntegerType(), True),
    StructField('Review_political', IntegerType(), True),
    StructField('Review_religious', IntegerType(), True),
])

In [25]:
df_survey = spark.read.csv('./data/SharedResponsesSurvey.csv', schema=survey_schema, header=True)

In [26]:
df_survey.printSchema()

root
 |-- ResponseID: string (nullable = true)
 |-- ExtendedSessionID: string (nullable = true)
 |-- UserID: string (nullable = true)
 |-- ScenarioOrder: integer (nullable = true)
 |-- Intervention: integer (nullable = true)
 |-- PedPed: integer (nullable = true)
 |-- Barrier: integer (nullable = true)
 |-- CrossingSignal: integer (nullable = true)
 |-- AttributeLevel: string (nullable = true)
 |-- ScenarioTypeStrict: string (nullable = true)
 |-- ScenarioType: string (nullable = true)
 |-- DefaultChoice: string (nullable = true)
 |-- NonDefaultChoice: string (nullable = true)
 |-- DefaultChoiceOmission: integer (nullable = true)
 |-- NumberOfCharacters: integer (nullable = true)
 |-- DiffNumberOfCharacters: integer (nullable = true)
 |-- Saved: integer (nullable = true)
 |-- Template: string (nullable = true)
 |-- DescriptionShown: integer (nullable = true)
 |-- LeftHand: integer (nullable = true)
 |-- UserCountry3: string (nullable = true)
 |-- Review_age: integer (nullable = true)
 |-- Review_education: string (nullable = true)
 |-- Review_gender: string (nullable = true)
 |-- Review_income: integer (nullable = true)
 |-- Review_political: integer (nullable = true)
 |-- Review_religious: integer (nullable = true)

In [28]:
df_survey.count()

11286141

In [27]:
df_survey.limit(50).toPandas()

,ResponseID,ExtendedSessionID,UserID,ScenarioOrder,Intervention,PedPed,Barrier,CrossingSignal,AttributeLevel,ScenarioTypeStrict,...,Template,DescriptionShown,LeftHand,UserCountry3,Review_age,Review_education,Review_gender,Review_income,Review_political,Review_religious
0,3ubu5Minm7ygqK3oa,-2147481563_6968366610050747.0,6968366610050750,13,0,0,0,0,Female,Gender,...,Desktop,0,0,RUS,32,bachelor,male,35000.0,NaN,NaN
1,FKd9Fje2tWt2sHi6v,-2147481563_6968366610050747.0,6968366610050750,8,0,1,0,0,Fat,Fitness,...,Desktop,0,0,RUS,32,bachelor,male,35000.0,NaN,NaN
2,J6WRHLj8exr4bNwTm,-2147481563_6968366610050747.0,6968366610050750,2,0,0,0,2,Young,Age,...,Desktop,0,1,RUS,32,bachelor,male,35000.0,NaN,NaN
3,KcYXwqS3rTrbqdTY2,-2147481563_6968366610050747.0,6968366610050750,1,0,1,0,2,Pets,Species,...,Desktop,0,1,RUS,32,bachelor,male,35000.0,NaN,NaN
4,ZQsAWst58jK9HcKvx,-2147481563_6968366610050747.0,6968366610050750,5,0,1,0,0,Fit,Fitness,...,Desktop,0,1,RUS,32,bachelor,male,35000.0,NaN,NaN
5,m4c66qhwmnqcCzxdX,-2147481563_6968366610050747.0,6968366610050750,4,0,0,0,1,Rand,Random,...,Desktop,0,0,RUS,32,bachelor,male,35000.0,NaN,NaN
6,nej5j6wM9YmiGHgA7,-2147481563_6968366610050747.0,6968366610050750,6,0,0,0,1,More,Utilitarian,...,Desktop,0,1,RUS,32,bachelor,male,35000.0,NaN,NaN
7,np7BxSz2LhNqXMAHj,-2147481563_6968366610050747.0,6968366610050750,3,0,1,0,0,Old,Age,...,Desktop,0,1,RUS,32,bachelor,male,35000.0,NaN,NaN
8,sibXCK6jno3M94BnR,-2147481563_6968366610050747.0,6968366610050750,12,0,1,0,1,Hoomans,Species,...,Desktop,0,1,RUS,32,bachelor,male,35000.0,NaN,NaN
9,w6kv36ap7rPR6FT4N,-2147481563_6968366610050747.0,6968366610050750,10,0,1,0,0,Low,Social Status,...,Desktop,0,0,RUS,32,bachelor,male,35000.0,NaN,NaN
10,zX9S9puJMRXnd54jY,-2147481563_6968366610050747.0,6968366610050750,7,0,0,0,0,More,Utilitarian,...,Desktop,0,0,RUS,32,bachelor,male,35000.0,NaN,NaN
11,zvm7Wg58vvue9xGhY,-2147481563_6968366610050747.0,6968366610050750,9,0,0,0,0,Female,Gender,...,Desktop,0,0,RUS,32,bachelor,male,35000.0,NaN,NaN
12,8whe449weo7kTYSLk,-2147456672_5603843098383972.0,5603843098383970,12,0,1,0,0,Rand,Fitness,...,Desktop,1,0,BEL,23,graduate,male,35000.0,NaN,0.0
13,QMcdnKDXB8aCjcyY7,-2147456672_5603843098383972.0,5603843098383970,7,0,0,1,0,Hoomans,Species,...,Desktop,0,1,BEL,23,graduate,male,35000.0,NaN,0.0
14,ex8Yry3j5xs2gQB9t,-2147456672_5603843098383972.0,5603843098383970,13,0,1,0,0,Fit,Fitness,...,Desktop,0,1,BEL,23,graduate,male,35000.0,NaN,0.0
15,gTsX5fFbjHHpeQWvf,-2147456672_5603843098383972.0,5603843098383970,1,0,0,0,0,Young,Age,...,Desktop,1,1,BEL,23,graduate,male,35000.0,NaN,0.0
16,i7ztRb5RdTu27QT4y,-2147456672_5603843098383972.0,5603843098383970,2,0,1,0,1,Male,Gender,...,Desktop,0,0,BEL,23,graduate,male,35000.0,NaN,0.0
17,pymKD6vrEsZSNw6e2,-2147456672_5603843098383972.0,5603843098383970,9,0,1,0,2,Old,Age,...,Desktop,0,1,BEL,23,graduate,male,35000.0,NaN,0.0
18,ryy93axFtmqfHtxL7,-2147456672_5603843098383972.0,5603843098383970,11,0,1,0,0,Pets,Species,...,Desktop,1,1,BEL,23,graduate,male,35000.0,NaN,0.0
19,tY7gMLWSygassFcJ4,-2147456672_5603843098383972.0,5603843098383970,10,0,1,0,0,Female,Gender,...,Desktop,0,0,BEL,23,graduate,male,35000.0,NaN,0.0
20,vwQkbHGcRhSWkzvs7,-2147456672_5603843098383972.0,5603843098383970,3,0,1,0,0,Less,Utilitarian,...,Desktop,0,1,BEL,23,graduate,male,35000.0,NaN,0.0
21,xgdpTjzHttfZRf773,-2147456672_5603843098383972.0,5603843098383970,5,0,1,0,2,Rand,Random,...,Desktop,0,0,BEL,23,graduate,male,35000.0,NaN,0.0
22,AGtnR6bonCrEsTQuL,-2147455629_9512031443725464.0,9512031443725470,10,0,1,0,2,Young,Age,...,Desktop,1,1,GHA,15,others,male,NaN,NaN,0.0
23,BXibYf8oe2SM8w6Xv,-2147455629_9512031443725464.0,9512031443725470,11,0,0,1,0,Fat,Fitness,...,Desktop,1,0,GHA,15,others,male,NaN,NaN,0.0
24,CRNzME6BLERc7jPoJ,-2147455629_9512031443725464.0,9512031443725470,4,0,0,0,0,Young,Age,...,Desktop,1,0,GHA,15,others,male,NaN,NaN,0.0
25,FXaJB4hwJr9vpYW7Y,-2147455629_9512031443725464.0,9512031443725470,1,0,1,0,2,High,Social Status,...,Desktop,1,1,GHA,15,others,male,NaN,NaN,0.0
26,HdCoZqjwzDvh2wRxE,-2147455629_9512031443725464.0,9512031443725470,5,0,0,0,0,More,Utilitarian,...,Desktop,1,1,GHA,15,others,male,NaN,NaN,0.0
27,J7dPtxAxc2t367GBj,-2147455629_9512031443725464.0,9512031443725470,7,0,0,0,2,More,Utilitarian,...,Desktop,1,0,GHA,15,others,male,NaN,NaN,0.0
28,LR6M85FT5XgAGNL7A,-2147455629_9512031443725464.0,9512031443725470,3,0,0,0,1,Male,Gender,...,Desktop,1,0,GHA,15,others,male,NaN,NaN,0.0
29,LvmuCSznRpivtm4LP,-2147455629_9512031443725464.0,9512031443725470,12,0,1,0,2,Fit,Fitness,...,Desktop,1,0,GHA,15,others,male,NaN,NaN,0.0
30,LzBoReazPbYBN9Ahd,-2147455629_9512031443725464.0,9512031443725470,2,0,0,0,1,Male,Gender,...,Desktop,1,0,GHA,15,others,male,NaN,NaN,0.0
31,T37PvkumXsAN8tbwf,-2147455629_9512031443725464.0,9512031443725470,8,0,1,0,0,Pets,Species,...,Desktop,0,0,GHA,15,others,male,NaN,NaN,0.0
32,ZZ8dJQ9XNrTdZSkWu,-2147455629_9512031443725464.0,9512031443725470,13,0,0,0,0,Pets,Species,...,Desktop,0,0,GHA,15,others,male,NaN,NaN,0.0
33,eSghy8Ye3vuQgXLyW,-2147455629_9512031443725464.0,9512031443725470,6,0,0,0,2,Rand,Random,...,Desktop,1,0,GHA,15,others,male,NaN,NaN,0.0
34,2JPQRdN9MfvsCxW9n,-2147423715_955468113069397.0,955468113069397,3,0,1,0,2,Male,Gender,...,Desktop,1,1,BRA,15,high,male,NaN,NaN,0.0
35,D6LdRrWqh28myFMZs,-2147423715_955468113069397.0,955468113069397,8,0,0,0,2,Rand,Random,...,Desktop,0,1,BRA,15,high,male,NaN,NaN,0.0
36,ENFZWYuJKkqztC7tk,-2147423715_955468113069397.0,955468113069397,10,0,1,0,0,Hoomans,Species,...,Desktop,0,0,BRA,15,high,male,NaN,NaN,0.0
37,PbdTargdEB7qmAtqw,-2147423715_955468113069397.0,955468113069397,4,0,0,1,0,More,Utilitarian,...,Desktop,0,0,BRA,15,high,male,NaN,NaN,0.0
38,Q5eQy7cPheLxfkE4f,-2147423715_955468113069397.0,955468113069397,1,0,1,0,0,Fat,Fitness,...,Desktop,0,1,BRA,15,high,male,NaN,NaN,0.0
39,S55ZKSsQn8Nh7yscF,-2147423715_955468113069397.0,955468113069397,11,0,0,1,0,Fit,Fitness,...,Desktop,1,1,BRA,15,high,male,NaN,NaN,0.0
40,ZaEJykeMraLWuoeXB,-2147423715_955468113069397.0,955468113069397,13,0,0,0,2,Pets,Species,...,Desktop,0,0,BRA,15,high,male,NaN,NaN,0.0
41,mMwLK7fHEbY2xdtL2,-2147423715_955468113069397.0,955468113069397,5,0,1,0,0,Female,Gender,...,Desktop,1,1,BRA,15,high,male,NaN,NaN,0.0
42,nQdQbcJGLgkktdwfa,-2147423715_955468113069397.0,955468113069397,12,0,0,0,0,Less,Utilitarian,...,Desktop,1,0,BRA,15,high,male,NaN,NaN,0.0
43,oqFsw2HNGcMavNDXs,-2147423715_955468113069397.0,955468113069397,7,0,0,0,2,Old,Age,...,Desktop,0,0,BRA,15,high,male,NaN,NaN,0.0
44,uf6o5rpzP83Lba5xN,-2147423715_955468113069397.0,955468113069397,9,0,0,1,0,Old,Age,...,Desktop,1,0,BRA,15,high,male,NaN,NaN,0.0
45,7YhXvwFC7xwp8PCLg,-2147422537_8735659664189848.0,8735659664189850,8,0,0,0,0,Less,Utilitarian,...,Desktop,0,0,USA,23,bachelor,male,50000.0,1.0,0.0
46,9baC2PcmDRyCsqR3n,-2147422537_8735659664189848.0,8735659664189850,9,0,1,0,1,More,Utilitarian,...,Desktop,0,0,USA,23,bachelor,male,50000.0,1.0,0.0
47,KuP7HL2Lr6w3tsmNx,-2147422537_8735659664189848.0,8735659664189850,4,0,0,0,0,Fit,Fitness,...,Desktop,0,1,USA,23,bachelor,male,50000.0,1.0,0.0
48,NwacQg6FYxPZTBgDr,-2147422537_8735659664189848.0,8735659664189850,7,0,1,0,0,Hoomans,Species,...,Desktop,0,0,USA,23,bachelor,male,50000.0,1.0,0.0
49,PtwSgPZy9skkCDrSu,-2147422537_8735659664189848.0,8735659664189850,10,0,0,0,2,High,Social Status,...,Desktop,0,1,USA,23,bachelor,male,50000.0,1.0,0.0